version: '3.7'

services:
  sryther:
    image: sryther/www
    networks:
      - proxy-all
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend.loadbalancer.stickyness=true"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=www_sryther"
        - "traefik.docker.network=proxy-all"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:sryther.fr"
        - "traefik.port=80"
        - "traefik.domain=sryther.fr,www.sryther.fr"
      placement:
        constraints:
          - node.hostname == riv-3

networks:
  proxy-all:
    external: true 
