version: '2'
services:
  sryther:
    build: .
    environment:
      - VIRTUAL_HOST=sryther.fr,www.sryther.fr
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sryther.fr,www.sryther.fr
      - LETSENCRYPT_EMAIL=paul.rey@sryther.fr

networks:
  default:
    external:
      name: proxy

